server:
  port: 8787
  tomcat:
    accesslog:
      buffered: true
      directory: logs
      enabled: false
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
    mbeanregistry:
      enabled: true
spring:
  application:
    name: dubbo-quickstart
  cache:
    cache-names: dictCache,cityCache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: dictHikariCP
  profiles:
    active: @spring.active@
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
  scan:
    base-packages: com.rookiefly.quickstart.dubbo.remote.impl
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    ivGeneratorClassname: org.jasypt.iv.RandomIvGenerator
management:
  endpoint:
    dubbo:
      enabled: true
    dubboconfigs:
      enabled: true
    dubboproperties:
      enabled: true
    dubboreferences:
      enabled: true
    dubboservices:
      enabled: true
    dubboshutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST
        allowed-origins: '*'
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.rookiefly.quickstart.dubbo.model
pagehelper:
  default-count: false