dubbo:
  application:
    name: ${spring.application.name}
  scan:
    base-packages: com.rookiefly.quickstart.dubbo.remote.impl
  registry:
    address: zookeeper://localhost:2181
  config-center:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
spring:
  datasource:
    initialization-mode: ALWAYS
    data: classpath:sql/data.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(W5p2CjSM+dafOGhlhKaKx3hriew7tlfwYWxdHJwYMdn7Px2o1uCEzsWGEq0UgJlZ)
    schema: classpath:sql/schema.sql
    url: jdbc:mysql://mysqldb:3306/dictdb?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 5000
    password: ''
    port: 6379
    timeout: 3000