server:
  port: 8787
  tomcat:
    accesslog:
      buffered: true
      directory: logs
      enabled: false
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
    mbeanregistry:
      enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: dubbo-quickstart
  cache:
    cache-names: dictCache,cityCache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=60s
    type: redis
    redis:
      time-to-live: 60s
      cache-null-values: true
  profiles:
    active: @spring.active@
  session:
    store-type: redis
    timeout: 1H
  jackson:
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh
    time-zone: GMT+8
    #不为空的属性才会序列化,具体属性可看JsonInclude.Include
    default-property-inclusion: NON_NULL
    serialization:
      # 返回的java.util.date转换成timestamp
      WRITE_DATES_AS_TIMESTAMPS: false
      # 对象为空时是否报错，默认true
      FAIL_ON_EMPTY_BEANS: true
    deserialization:
      # 常用,json中含pojo不存在属性时是否失败报错,默认true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      # 使用getter取代setter探测属性，如类中含getName()但不包含name属性与setName()，传输的vo json格式模板中依旧含name属性
      USE_GETTERS_AS_SETTERS: true
    parser:
      # 是否允许出现单引号,默认false
      ALLOW_SINGLE_QUOTES: true
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    threadname: defaultProvider
    threadpool: watching
  scan:
    base-packages: com.rookiefly.quickstart.dubbo.remote.impl
  consumer:
    filter: -sentinel.dubbo.consumer.filter
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    ivGeneratorClassname: org.jasypt.iv.RandomIvGenerator
management:
  endpoint:
    dubbo:
      enabled: true
    dubboconfigs:
      enabled: true
    dubboproperties:
      enabled: true
    dubboreferences:
      enabled: true
    dubboservices:
      enabled: true
    dubboshutdown:
      enabled: true
    health:
      show-details: always
      dubbo:
        enabled: true
        status:
          extras: load,threadpool
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST
        allowed-origins: '*'
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.rookiefly.quickstart.dubbo.model
pagehelper:
  default-count: false