dubbo:
  application:
    name: ${spring.application.name}
  scan:
    base-packages: com.rookiefly.quickstart.dubbo.remote.impl
  registry:
    address: zookeeper://localhost:2181
  config-center:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
spring:
  datasource:
    initialization-mode: ALWAYS
    data: classpath:sql/data.sql
    password: ENC(W5p2CjSM+dafOGhlhKaKx3hriew7tlfwYWxdHJwYMdn7Px2o1uCEzsWGEq0UgJlZ)
    schema: classpath:sql/schema-h2.sql
    url: jdbc:h2:mem:dictdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 5000
    password: ''
    port: 6379
    timeout: 3000
#com.rocketmq.sendMessageWithVIPChannel: false
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: dubbo-quickstart-group
#  sms:
#    topic: sms-topic