version: "3.5"

services:
  zk1:
    image: zookeeper
    #restart: always
    container_name: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    networks:
      - dubbo-net

  zk2:
    image: zookeeper
    #restart: always
    container_name: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    networks:
      - dubbo-net

  zk3:
    image: zookeeper
    #restart: always
    container_name: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    networks:
      - dubbo-net

  mysqldb:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dictdb
      MYSQL_USER: rookiefly
      MYSQL_PASSWORD: rookiefly
    ports:
      - "3306:3306"
    networks:
      - dubbo-net

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    #restart: always
    networks:
      - dubbo-net

  rmqnamesrv:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rmqs/logs:/opt/logs
      - ./rmqs/store:/opt/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    command: [ "sh","mqnamesrv" ]
    networks:
      - dubbo-net

  rmqbroker:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rmq/logs:/opt/logs
      - ./rmq/store:/opt/store
      - ./rmq/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    command: [ "sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true" ]
    depends_on:
      - rmqnamesrv
    networks:
      - dubbo-net

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8180:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      - dubbo-net
  dubbo-admin:
    image: rookiefly/dubbo-admin:latest
    container_name: dubbo-admin
    ports:
      - 8089:8080
    networks:
      - dubbo-net
    environment:
      - admin.registry.address=zookeeper://zk1:2181?backup=zk2:2181,zk3:2181
      - admin.config-center=zookeeper://zk1:2181?backup=zk2:2181,zk3:2181
      - admin.metadata-report.address=zookeeper://zk1:2181?backup=zk2:2181,zk3:2181
    depends_on:
      - zk1
      - zk2
      - zk3

  sentinel-dashboard:
    image: rookiefly/sentinel-dashboard:latest
    container_name: sentinel-dashboard
    ports:
      - 8280:8280
    networks:
      - dubbo-net

  dubbo-quickstart:
    image: rookiefly/dubbo-quickstart:latest
    container_name: dubbo-quickstart
    ports:
      - 8787:8787
    networks:
      - dubbo-net
    environment:
      - dubbo.registry.address=zookeeper://zk1:2181?backup=zk2:2181,zk3:2181
      - dubbo.config-center.address=zookeeper://zk1:2181?backup=zk2:2181,zk3:2181
      - dubbo.metadata-report.address=zookeeper://zk1:2181?backup=zk2:2181,zk3:2181
      - jasypt.encryptor.password=123456
      - rocketmq.name-server=rmqnamesrv:9876
      - spring.redis.host=redis
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dictdb?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      - JAVA_OPTS=-Dcsp.sentinel.dashboard.server=sentinel-dashboard:8280 -Dproject.name=sentinel-dubbo-quickstart
    depends_on:
      - zk1
      - zk2
      - zk3
      - dubbo-admin
      - sentinel-dashboard

networks:
  dubbo-net:
    name: dubbo-net
    driver: bridge
