version: "3.5"

services:
  zk1:
    image: zookeeper
    container_name: zk1
#    ports:
#      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - zoo-data:/var/lib/zookeeper/data
      - zoo-log:/var/lib/zookeeper/log
    networks:
      - dubbo-net

  mysqldb:
    image: rookiefly/mysql:latest
    container_name: mysqldb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dictdb
      MYSQL_USER: rookiefly
      MYSQL_PASSWORD: rookiefly
#    ports:
#      - "3306:3306"
    networks:
      - dubbo-net

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
#    ports:
#      - "6379:6379"
    networks:
      - dubbo-net

  rmqconsole:
    image: rookiefly/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8180:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - namesrv
    networks:
      - dubbo-net

  namesrv:
    image: apacherocketmq/rocketmq:4.8.0
    container_name: rmqnamesrv
#    ports:
#      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: nohup sh mqnamesrv &
    networks:
      - dubbo-net

  broker:
    image: apacherocketmq/rocketmq:4.8.0
    container_name: rmqbroker
#    ports:
#      - 10909:10909
#      - 10911:10911
#      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-4.8.0/conf/broker.conf
    command: nohup sh mqbroker -n namesrv:9876 -c /opt/rocketmq-4.8.0/conf/broker.conf &
    depends_on:
      - namesrv
    networks:
      - dubbo-net

#   broker1:
#     image: apacherocketmq/rocketmq:4.8.0
#     container_name: rmqbroker-b
# #    ports:
# #      - 10929:10909
# #      - 10931:10911
# #      - 10932:10912
#     environment:
#       - NAMESRV_ADDR=namesrv:9876
#     volumes:
#       - ./data1/broker/logs:/home/rocketmq/logs
# #      - ./data1/broker/store:/home/rocketmq/store
#       - ./data1/broker/conf/broker.conf:/opt/rocketmq-4.8.0/conf/broker.conf
#     command: nohup sh mqbroker -n namesrv:9876 -c /opt/rocketmq-4.8.0/conf/broker.conf &
#     depends_on:
#       - namesrv
#     networks:
#       - dubbo-net

  dubbo-admin:
    image: rookiefly/dubbo-admin:latest
    container_name: dubbo-admin
    ports:
      - 8089:8080
    networks:
      - dubbo-net
    environment:
      - admin.registry.address=zookeeper://zk1:2181
      - admin.config-center=zookeeper://zk1:2181
      - admin.metadata-report.address=zookeeper://zk1:2181
    depends_on:
      - zk1

  sentinel-dashboard:
    image: rookiefly/sentinel-dashboard:latest
    container_name: sentinel-dashboard
    ports:
      - 8280:8280
    networks:
      - dubbo-net

  dubbo-quickstart:
    image: rookiefly/dubbo-quickstart:latest
    container_name: dubbo-quickstart
    ports:
      - 8787:8787
    networks:
      - dubbo-net
    environment:
      - jasypt.encryptor.password=123456
      - com.rocketmq.sendMessageWithVIPChannel=false
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Dcsp.sentinel.dashboard.server=sentinel-dashboard:8280 -Dproject.name=sentinel-dubbo-quickstart
    depends_on:
      - zk1
      - redis
      - mysqldb

networks:
  dubbo-net:
    name: dubbo-net
    driver: bridge
volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
  zoo-data:
    driver: local
  zoo-log:
    driver: local
